### ISSUE TITLE
Joining not possible

### ISSUE THREAD

**Issue by Alphayeeeet** [Server24-7/CloudSpigot#4]
There is no exception in the console and the server is starting normally, but if I want to join by localhost, it says, that there is no existing server running (port is 25565). The error: https://prnt.sc/qjbaig

Please help @Linux-4

**Comment by AlphaPlays** [comment]
@Linux-4

**Comment by Linux4** [comment]
Try Running the Server with Java 11+ or use CloudSpigot-1.12

Edit: should be fixed by downgrading netty to v4.1.36
@AlphaPlays

**Comment by Alphayeeeet** [comment]
Why shoud I open it with JRE 11? And I need the source of CloudSpigot1.8

**Comment by Alphayeeeet** [comment]
Maybe it is possible to talk with you on Discord? (Ich weiß nicht ob du deutsch sprichst aber dann wäre das ganz hilfreich).

**Comment by Linux4** [comment]
Forget JRE11 i fixed it by downgrading netty

**Comment by Alphayeeeet** [comment]
OK nice

**Comment by Linux4** [comment]
OK, auf discord heiße ich Linux4#7646, falls es noch Probleme gibt adde mich da mal
